### ISSUE TITLE
Unnecessary method implementation

### ISSUE THREAD

**Issue by rozsival** [wavevision/development-utils#1]
This should be replaced with `Wavevision\Utils\Strings::camelCaseToDashCase`

https://github.com/wavevision/development-utils/blob/9cbec2e7d110befce1329c4a616634d8be9a33b1/src/DevelopmentUtils/GenerateConstants.php#L29

**Comment by jfilla** [comment]
We should implement camelCaseToSnakeCase function at https://github.com/wavevision/utils and use it here.
